### ISSUE TITLE
Choice Feature

### ISSUE THREAD

**Issue by queball1999** [Game351-Group/Assignment2#5]
**CHOICE FEATURES** (Pick 1 of 3). Your game must implement 1 of 3 choices listed in this section. Each feature in this section is worth 16% of the assignment grade. You may also implement a second feature for 10% extra credit. 

**5. Dynamic Spawn:** Allow the player to spawn a new hovercraft with each press of the “1”, “2”, or “3” keys (one key for each type). The next car should not pop into existence on top of an existing hovercraft – try to spawn in separate places. Up to 10 hovercraft may be spawned into the world. Hint: You may spawn a hovercraft at any reasonable place, i.e. either to random or predictable locations, so long as a new car doesn’t overlap an existing one and remains on the terrain surface.  

**6. Laser-Firing Car:** Make one hovercraft fire a laser bolt each time the player presses the spacebar. Be sure to identify which car fires the laser in your readme. Laser bolts should emanate from the front, center of the car and move at a high (yet visible) rate of speed. The laser bolts may be modeled using scaled cylinders. You should spawn and destroy the laser bolts dynamically. Hint: Think Star Wars effects here. The sample program (Example 2) from the Lecture 2 video may help. You may make the laser bolt glow green or red, if you wish, using materials and a Bloom filter. 

**7. More Realistic Effects:** Make your scene more audibly and visually immersive by adding the following two effects to your hovercraft: a) Make the hovercraft engines sound like they are speeding up and slowing down when starting and stopping, respectively. Hint: Manipulating the pitch and volume of the Audiosource component will be useful here. b) Make the engines, lights, and other Tron-like features of each hovercraft glow. Add a “hover engine” block to the bottom of each car that also glows. Hint:  Bloom effects will be very useful here; most of the post-processing pipeline for Bloom is already set up for you in the assignment 2 template scene. Your results should look similar to the You Tube example (above).

**Comment by ArmsTina** [comment]
6. Laser-Firing Car: Make one hovercraft fire a laser bolt each time the player presses the spacebar. Be sure to identify which car fires the laser in your readme. Laser bolts should emanate from the front, center of the car and move at a high (yet visible) rate of speed. The laser bolts may be modeled using scaled cylinders. You should spawn and destroy the laser bolts dynamically. Hint: Think Star Wars effects here. The sample program (Example 2) from the Lecture 2 video may help. You may make the laser bolt glow green or red, if you wish, using materials and a Bloom filter.

7. More Realistic Effects: Make your scene more audibly and visually immersive by adding the following two effects to your hovercraft: a) Make the hovercraft engines sound like they are speeding up and slowing down when starting and stopping, respectively. Hint: Manipulating the pitch and volume of the Audiosource component will be useful here. b) Make the engines, lights, and other Tron-like features of each hovercraft glow. Add a “hover engine” block to the bottom of each car that also glows. Hint: Bloom effects will be very useful here; most of the post-processing pipeline for Bloom is already set up for you in the assignment 2 template scene. Your results should look similar to the You Tube example (above).
